### ISSUE TITLE
How to use a Verge Wallet in Python3?

### ISSUE THREAD

**Issue by shuggaah** [vergecurrency/verge-python3#8]
Hey,

I want to make an Django App which is able to send and receive XVG with my Wallets. First starting point would be to use the Wallet in a Python console. Is there an Documentation for this or can Someone help me with that?

Sorry if this is not the right place to ask...

**Comment by P1R** [comment]
its quite easy, actually I did something like that... All you need is to take a look at the sphinx documentation that is integrated into the repository:

[verge-python3 Documentation](https://github.com/vergecurrency/verge-python3/tree/master/doc )
